name: Build Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt pyinstaller

      - name: Build with PyInstaller (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --onefile --noconsole ^
            --icon=logo.ico ^
            --add-data "templates;templates" ^
            --add-data "static;static" ^
            app.py

      - name: Build with PyInstaller (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller --onefile --noconsole \
            --icon=logo.png \
            --add-data "templates:templates" \
            --add-data "static:static" \
            app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ProTKD-${{ matrix.os }}
          path: dist/*
